In [89]:
import pandas as pd
import seaborn as sns
%matplotlib inline

In [90]:
df_condos = pd.read_csv("/Users/maryam/Downloads/real_estate.condo_full.csv");

/Users/maryam/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (1,2,9,24,26,45,70,80,82,91,95,96,97,98,99,100,101,102,103,104,106,107,141,145,146,147,149,208,209,210,211,215,216,222,228,240,241,242,243,244,245,248) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [92]:
pd.set_option('display.max_rows',300)
pd.set_option('display.max_columns',400)
df_condos.head()

,A_c,Access_prop1,Access_prop2,Ad_text,Addl_mo_fee,Addr,All_inc,Apt_num,Area,Area_code,Ass_year,Bath_tot,Bldg_amen1_out,Bldg_amen2_out,Bldg_amen3_out,Bldg_amen4_out,Bldg_amen5_out,Bldg_amen6_out,Br,Br_plus,Bsmt1_out,Bsmt2_out,Cable,Cac_inc,Cd,Central_vac,Cert_lvl,Cndsold_xd,Com_coopb,Comel_inc,Community,Community_code,Cond,Cond_txinc,Condo_corp,Condo_exp,Constr1_out,Constr2_out,Corp_num,County,Cross_st,Den_fr,Disp_addr,Dom,Dt_sus,Dt_ter,Elevator,Energy_cert,Ens_lndry,Extras,Fpl_num,Fuel,Furnished,Gar,Gar_type,Green_pis,Handi_equipped,Heat_inc,Heating,Hydro_inc,Input_date,Insur_bldg,Internet,Kit_plus,Laundry,Laundry_lev,Ld,Level1,Level10,Level11,Level12,Level2,Level3,Level4,Level5,Level6,Level7,Level8,Level9,Locker,Locker_lev_unit,Locker_num,Locker_unit,Lp_dol,Lsc,Maint,Ml_num,Mmap_col,Mmap_page,Mmap_row,Municipality,Municipality_code,Municipality_district,Num_kit,Occ,Oh_date1,Oh_date2,Oh_date3,Oh_dt_stamp,Oh_from1,Oh_from2,Oh_from3,Oh_to1,Oh_to2,Oh_to3,Orig_dol,Outof_area,Parcel_id,Park_chgs,Park_desig,Park_desig_2,Park_fac,Park_lgl_desc1,Park_lgl_desc2,Park_spc1,Park_spc2,Park_spcs,Patio_ter,Perc_dif,Pets,Pix_updt,Pr_lsc,Prkg_inc,Prop_feat1_out,Prop_feat2_out,Prop_feat3_out,Prop_feat4_out,Prop_feat5_out,Prop_feat6_out,Prop_mgmt,Pvt_ent,Retirement,Rltr,Rm10_dc1_out,Rm10_dc2_out,Rm10_dc3_out,Rm10_len,Rm10_out,Rm10_wth,Rm11_dc1_out,Rm11_dc2_out,Rm11_dc3_out,Rm11_len,Rm11_out,Rm11_wth,Rm12_dc1_out,Rm12_dc2_out,Rm12_dc3_out,Rm12_len,Rm12_out,Rm12_wth,Rm1_dc1_out,Rm1_dc2_out,Rm1_dc3_out,Rm1_len,Rm1_out,Rm1_wth,Rm2_dc1_out,Rm2_dc2_out,Rm2_dc3_out,Rm2_len,Rm2_out,Rm2_wth,Rm3_dc1_out,Rm3_dc2_out,Rm3_dc3_out,Rm3_len,Rm3_out,Rm3_wth,Rm4_dc1_out,Rm4_dc2_out,Rm4_dc3_out,Rm4_len,Rm4_out,Rm4_wth,Rm5_dc1_out,Rm5_dc2_out,Rm5_dc3_out,Rm5_len,Rm5_out,Rm5_wth,Rm6_dc1_out,Rm6_dc2_out,Rm6_dc3_out,Rm6_len,Rm6_out,Rm6_wth,Rm7_dc1_out,Rm7_dc2_out,Rm7_dc3_out,Rm7_len,Rm7_out,Rm7_wth,Rm8_dc1_out,Rm8_dc2_out,Rm8_dc3_out,Rm8_len,Rm8_out,Rm8_wth,Rm9_dc1_out,Rm9_dc2_out,Rm9_dc3_out,Rm9_len,Rm9_out,Rm9_wth,Rms,Rooms_plus,S_r,Secgrd_sys,Share_perc,Shore_allow,Shoreline_exp,Sp_dol,Spec_des1_out,Spec_des2_out,Spec_des3_out,Spec_des4_out,Spec_des5_out,Spec_des6_out,Sqft,St,St_dir,St_num,St_sfx,Status,Stories,Style,Taxes,Td,Timestamp_sql,Tot_park_spcs,Tour_url,Tv,Type_own1_out,Type_own_srch,Uffi,Unavail_dt,Unit_num,Vend_pis,Vtour_updt,Water_body,Water_feat1,Water_feat2,Water_feat3,Water_feat4,Water_feat5,Water_front,Water_inc,Water_type,Wcloset_p1,Wcloset_p2,Wcloset_p3,Wcloset_p4,Wcloset_p5,Wcloset_t1,Wcloset_t1lvl,Wcloset_t2,Wcloset_t2lvl,Wcloset_t3,Wcloset_t3lvl,Wcloset_t4,Wcloset_t4lvl,Wcloset_t5,Wcloset_t5lvl,Xd,Xdtd,Yr,Yr_built,Zip,Zoning,_id
0,NaN,NaN,NaN,Parking Space Only. Extra Parking Space For Ex...,NaN,25 Town Centre Crt,NaN,NaN,Toronto,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5%,NaN,Bendale,01.E09.1110,NaN,N,tscp,NaN,NaN,NaN,2190.0,Ontario,Mccowan/401,NaN,Y,64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2018-11-24 00:00:00.0,Y,Y,NaN,NaN,NaN,2018-11-24 00:00:00.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000.0,New,0.00,E4310459,33.0,111.0,G,Toronto,01.E09,Toronto E09,NaN,30Days/Tba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000.0,NaN,NaN,NaN,Owned,NaN,Undergrnd,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2018-11-24 09:45:35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Living Properties Inc.,NaN,NaN,"HOMELIFE TODAY REALTY LTD., BROKERAGE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Town Centre,NaN,25,Crt,A,A,NaN,0.00,NaN,2018-11-24 09:45:35.0,1.0,NaN,NaN,Parking Space,@.,NaN,NaN,54,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-03-31 00:00:00.0,NaN,2018.0,NaN,M1P0B4,NaN,5c4e60d17b48a023c33eac4d
1,Central Air,NaN,NaN,"A Brand New Condo Community, Located Close To ...",NaN,1328 Birchmount Rd,NaN,113,Toronto,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,None,NaN,N,Y,NaN,N,NaN,NaN,2.5%,Y,Wexford-Maryvale,01.E04.1090,NaN,N,TSCC,S,Brick,NaN,2504.0,Ontario,Birchmount/Lawrence,N,Y,54.0,NaN,NaN,NaN,NaN,N,"Window Coverings, Fridge, Stove, Washer, Dryer...",N,Gas,NaN,0.0,None,NaN,NaN,Y,Forced Air,N,2018-12-04 00:00:00.0,Y,Y,NaN,NaN,Main,2018-12-04 00:00:00.0,Flat,NaN,NaN,NaN,Flat,Flat,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,338000.0,New,373.37,E4316456,30.0,110.0,J,Toronto,01.E04,Toronto E04,1.0,Tba/Immediate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,338000.0,NaN,NaN,NaN,None,NaN,None,NaN,NaN,NaN,NaN,0.0,None,NaN,Restrict,2018-12-27 09:34:01.0,NaN,N,Library,School,NaN,NaN,NaN,NaN,Duka Property Management,NaN,NaN,"HOMELIFE/VISION REALTY INC., BROKERAGE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Combined W/Dining,NaN,NaN,NaN,Living,NaN,Combined W/Living,NaN,NaN,NaN,Dining,NaN,Open Concept,Combined W/Living,NaN,NaN,Kitchen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,Sale,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,600-699,Birchmount,NaN,1328,Rd,A,1,Bachelor/Studio,1.00,NaN,2018-12-27 09:33:56.0,0.0,NaN,NaN,Condo Apt,C.,NaN,NaN,113,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,4.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-04-04 00:00:00.0,NaN,2018.0,NaN,M1R3A7,Residential,5c4e60d17b48a023c33eac4e
2,Wall Unit,NaN,NaN,"Rarely Offered, Bachelor Unit In The Heart Of ...",NaN,123 Woodbine Ave,N,322,Toronto,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,None,NaN,N,N,NaN,NaN,NaN,NaN,1/2 Month's Rent,Y,The Beaches,01.E02.1390,NaN,NaN,YCC,W,Brick,NaN,210.0,Ontario,Woodbine / Queen St East,N,Y,24.0,NaN,NaN,NaN,NaN,NaN,"Fridge, Stove, Dishwasher, Microwave. Tv, Murp...",Y,Electric,Part,0.0,None,NaN,NaN,Y,Baseboard,Y,2019-01-03 00:00:00.0,Y,Y,NaN,Shared,NaN,2019-01-03 00:00:00.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,1550.0,New,NaN,E4328538,26.0,121.0,S,Toronto,01.E02,Toronto E02,1.0,Immediate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1550.0,NaN,NaN,NaN,Common,NaN,Surface,NaN,NaN,NaN,NaN,1.0,Open,NaN,Restrict,2019-01-03 13:30:46.0,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,Eastway Property Management,Y,NaN,"SUTTON GROUP-ASSOCIATES REALTY INC., BROKERAGE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,Lease,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,0-499,Woodbine,NaN,123,Ave,A,3,Bachelor/Studio,NaN,NaN,2019-01-09 11:50:55.0,1.0,NaN,NaN,Condo Apt,C.,NaN,NaN,322,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,3.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-03 00:00:00.0,NaN,NaN,NaN,M4L3V8,NaN,5c4e60d17b48a023c33eac4f
3,Window Unit,NaN,NaN,"Three-Bedroom Home, Conveniently Located. The ...",NaN,1100 Oxford St,NaN,21,Durham,10,NaN,1,Bbqs Allowed,Visitor Parking,NaN,NaN,NaN,NaN,3.0,1.0,Full,Part Fin,N,N,NaN,N,NaN,NaN,2.5%,Y,Lakeview,10.07.0140,NaN,N,DCC,N,Brick,NaN,27.0,Ontario,Oxford/Wentworth,N,Y,60.0,NaN,NaN,N,NaN,Y,Ideal For Investment. Rent Covers Mortgage And...,N,Electric,NaN,0.0,None,NaN,NaN,Y,Baseboard,Y,2018-11-28 00:00:00.0,Y,Y,NaN,NaN,Lower,2018-11-28 00:00:00.0,Main,NaN,NaN,NaN,Main,Main,2nd,2nd,2nd,NaN,NaN,NaN,None,NaN,NaN,NaN,219500.0,Pc,620.81,E4312425,27.0,277.0,U,Oshawa,10.07,Oshawa,1.0,60-90 Days,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,239400.0,NaN,NaN,NaN,Exclusive,NaN,Surface,NaN,NaN,NaN,NaN,1.0,Terr,NaN,Restrict,2018-11-28 08:48:14.0,New,Y,Fenced Yard,Hospital,Lake Access,Park,School,School Bus Route,Baybrook Property Management,NaN,NaN,"ROYAL LEPAGE TERREQUITY REALTY, BROKERAGE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Window,NaN,NaN,2.75,Kitchen,2.44,L-Shaped Room,Combined W/Dining,NaN,5.50,Living,3.35,L-Shaped Room,Combined W/Living,NaN,2.9,Dining,2.50,NaN,NaN,NaN,5.2,Master,3.35,NaN,NaN,NaN,3.35,2nd Br,2.75,NaN,NaN,NaN,3.35,3rd Br,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,1.0,Sale,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,900-999,Oxford,NaN,1100,St,A,1,2-Storey,1561.71,NaN,2019-01-04 14:46:24.0,1.0,NaN,NaN,Condo Townhouse,T.,No,NaN,21,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,4.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-03-28 00:00:00.0,NaN,2018.0,NaN,L1J6G4,NaN,5c4e60d17b48a023c33eac50
4,Central Air,NaN,NaN,Great Location.Close To Everything .Luxury Gre...,NaN,18 Harding Blvd,NaN,Ph 206,York,9,NaN,2,Concierge,Exercise Room,Gym,Party/Meeting Room,NaN,NaN,2.0,NaN,None,NaN,N,Y,NaN,NaN,NaN,NaN,2.5%,Y,Harding,09.04.0100,NaN,N,YRSC,S,Concrete,NaN,1174.0,Ontario,Yonge/Harding,N,Y,90.0,NaN,NaN,NaN,NaN,Y,NaN,N,Gas,NaN,1.0,Undergrnd,NaN,NaN,Y,Forced Air,N,2018-10-29 00:00:00.0,Y,Y,NaN,NaN,NaN,2018-10-29 00:00:00.0,Main,NaN,NaN,NaN,Main,Main,Main,Main,NaN,NaN,NaN,NaN,Owned,NaN,NaN,NaN,588800.0,Pc,507.95,N4289314,NaN,NaN,NaN,Richmond Hill,09.04,Richmond Hill,1.0,Tba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,598800.0,NaN,NaN,NaN,Owned,NaN,Undergrnd,NaN,NaN,NaN,NaN,1.0,Open,NaN,Restrict,2018-10-29 14:29:29.0,New,Y,Clear View,Hospital,Library,Park,Public Transit,NaN,First Service Residential,NaN,NaN,"TOP CANADIAN REALTY INC., BROKERAGE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hardwood Floor,Combined W/Dining,W/O To Balcony,6.25,Living,4.75,Hardwood Floor,Combined W/Living,NaN,4.78,Dining,6.25,Granite Counter,Breakfast Bar,Custom Backsplash,3.1,Kitchen,2.95,W/O To Balcony,W/I Closet,5 Pc Ensuite,3.6,Master,3.10,Large Window,Closet,NaN,3.15,2nd Br,2.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,Sale,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,1000-1199,Harding,NaN,18,Blvd,A,Ph,Apartment,3218.49,NaN,2018-12-04 12:56:35.0,1.0,NaN,NaN,Condo Apt,C.,NaN,NaN,206,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,5.0,3.0,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-03-22 00:00:00.0,NaN,2018.0,6-10,L4C 1S6,NaN,5c4e60d17b48a023c33eac51

In [81]:
list_of_columns = ['Ml_num','Unit_num','Apt_num','Addl_mo_fee','All_inc','Lp_dol','S_r','Input_date','Maint','Taxes','Status']
df = df_condos[list_of_columns]

In [82]:
df.head()

,Ml_num,Unit_num,Apt_num,Addl_mo_fee,All_inc,Lp_dol,S_r,Input_date,Maint,Taxes,Status
0,E4310459,54,NaN,NaN,NaN,50000.0,Sale,2018-11-24 00:00:00.0,0.00,0.00,A
1,E4316456,113,113,NaN,NaN,338000.0,Sale,2018-12-04 00:00:00.0,373.37,1.00,A
2,E4328538,322,322,NaN,N,1550.0,Lease,2019-01-03 00:00:00.0,NaN,NaN,A
3,E4312425,21,21,NaN,NaN,219500.0,Sale,2018-11-28 00:00:00.0,620.81,1561.71,A
4,N4289314,206,Ph 206,NaN,NaN,588800.0,Sale,2018-10-29 00:00:00.0,507.95,3218.49,A

In [83]:
df.loc[df['S_r'] == 'Lease']

,Ml_num,Unit_num,Apt_num,Addl_mo_fee,All_inc,Lp_dol,S_r,Input_date,Maint,Taxes,Status
2,E4328538,322,322,NaN,N,1550.0,Lease,2019-01-03 00:00:00.0,NaN,NaN,A
7,E4329715,3,Unit 2,NaN,N,3500.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
14,E4317402,1,301,NaN,N,1350.0,Lease,2018-12-05 00:00:00.0,0.0,NaN,A
15,E4319152,04,1104,NaN,N,1850.0,Lease,2018-12-07 00:00:00.0,NaN,NaN,A
18,E4329395,2505,2505,NaN,N,2000.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
22,E4310550,0,NaN,NaN,Y,2895.0,Lease,2018-11-24 00:00:00.0,NaN,NaN,A
23,E4316679,03,1303,NaN,N,2100.0,Lease,2018-12-04 00:00:00.0,NaN,NaN,A
24,E4327584,10,310,NaN,N,1650.0,Lease,2019-01-02 00:00:00.0,NaN,NaN,A
31,E4314076,09,709,NaN,N,1750.0,Lease,2018-11-30 00:00:00.0,NaN,NaN,A
39,E4316498,05,Ph 05,NaN,N,6000.0,Lease,2018-12-04 00:00:00.0,NaN,NaN,A
44,E4329606,4,609-4,NaN,N,1700.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
52,E4329443,9,1609,NaN,N,2300.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
53,E4316611,04,Bedroom,NaN,N,1100.0,Lease,2018-12-04 00:00:00.0,NaN,NaN,A
54,E4329220,20,2420,NaN,N,2100.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
57,E4330443,01,501,NaN,N,2450.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
64,E4329473,303,303,NaN,N,1295.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
65,C4342920,11,1311,NaN,N,2500.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
67,E4322140,23,23,NaN,N,2550.0,Lease,2018-12-13 00:00:00.0,NaN,NaN,A
74,E4316597,04,1504,NaN,N,2350.0,Lease,2018-12-04 00:00:00.0,NaN,NaN,A
78,E4316405,184,184,NaN,N,2300.0,Lease,2018-12-04 00:00:00.0,NaN,NaN,A
80,E4316960,7,1507,NaN,N,2500.0,Lease,2018-12-05 00:00:00.0,NaN,NaN,A
88,E4314208,04,604,NaN,N,2200.0,Lease,2018-11-30 00:00:00.0,NaN,NaN,A
89,E4321191,19,1019,NaN,N,2000.0,Lease,2018-12-12 00:00:00.0,NaN,NaN,A
92,E4322154,09,1809,NaN,Y,2800.0,Lease,2018-12-13 00:00:00.0,NaN,NaN,A
93,E4332008,7,907,NaN,N,1500.0,Lease,2019-01-08 00:00:00.0,NaN,NaN,A
96,E4330598,03,3303,NaN,N,2000.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
101,E4326548,8,908,NaN,N,1900.0,Lease,2018-12-28 00:00:00.0,NaN,NaN,A
102,E4328010,13,1113,NaN,N,1950.0,Lease,2019-01-02 00:00:00.0,NaN,NaN,A
103,E4327712,32,NaN,NaN,N,2600.0,Lease,2019-01-02 00:00:00.0,NaN,NaN,A
104,E4329656,18,1919,NaN,N,2000.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
105,E4331048,82,82,NaN,N,1799.0,Lease,2019-01-07 00:00:00.0,0.0,NaN,A
109,E4331111,07,807,NaN,N,1800.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
116,E4327850,10,510,NaN,N,2050.0,Lease,2019-01-02 00:00:00.0,NaN,NaN,A
129,E4336279,01,701,NaN,N,2350.0,Lease,2019-01-14 00:00:00.0,NaN,NaN,A
130,E4325378,10,810,NaN,N,2650.0,Lease,2018-12-21 00:00:00.0,0.0,NaN,A
131,E4326073,09,2209,NaN,N,2300.0,Lease,2018-12-24 00:00:00.0,NaN,NaN,A
138,C4342908,11,1211,NaN,N,2250.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
139,E4332218,02,902,NaN,N,2200.0,Lease,2019-01-08 00:00:00.0,NaN,NaN,A
141,E4330856,12,1715,NaN,N,1950.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
146,E4329253,12,1712,NaN,N,1675.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
148,E4331280,15,3415,NaN,N,1850.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
153,C4342901,01,1701,NaN,N,2600.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
154,E4327000,15,415,NaN,N,1880.0,Lease,2018-12-31 00:00:00.0,NaN,NaN,A
156,E4332885,10,1210,NaN,N,1975.0,Lease,2019-01-09 00:00:00.0,NaN,NaN,A
161,E4329763,6,6,NaN,N,2650.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
164,E4336424,0,208,NaN,N,2500.0,Lease,2019-01-14 00:00:00.0,NaN,NaN,A
166,W4342942,15,1629,NaN,N,1930.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
167,E4320694,2,3102,NaN,N,2400.0,Lease,2018-12-11 00:00:00.0,NaN,NaN,A
169,E4324340,9,810,NaN,N,1900.0,Lease,2018-12-19 00:00:00.0,NaN,NaN,A
174,E4332896,07,#207,NaN,N,2200.0,Lease,2019-01-09 00:00:00.0,NaN,NaN,A
177,C4342905,05,1115,NaN,N,2000.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
179,E4334932,14,1414,NaN,N,1875.0,Lease,2019-01-11 00:00:00.0,NaN,NaN,A
184,E4336471,312,312,NaN,N,1850.0,Lease,2019-01-14 00:00:00.0,NaN,NaN,A
185,E4316219,3335,3335,NaN,N,2100.0,Lease,2018-12-04 00:00:00.0,NaN,NaN,A
188,C4342931,4,2504,NaN,N,2200.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
198,E4334144,3,1003,NaN,N,2300.0,Lease,2019-01-10 00:00:00.0,NaN,NaN,A
200,E4335440,10,510,NaN,N,1900.0,Lease,2019-01-12 00:00:00.0,NaN,NaN,A
202,E4323846,14,2014,NaN,N,2200.0,Lease,2018-12-18 00:00:00.0,NaN,NaN,A
203,E4322610,19,19,NaN,N,2150.0,Lease,2018-12-14 00:00:00.0,NaN,NaN,A
207,E4330666,14,414,NaN,N,2100.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
209,E4334266,1,1808,NaN,N,700.0,Lease,2019-01-10 00:00:00.0,NaN,NaN,A
212,E4333152,03,303,NaN,N,3500.0,Lease,2019-01-09 00:00:00.0,NaN,NaN,A
213,E4328090,2,Unit 3,NaN,N,2800.0,Lease,2019-01-02 00:00:00.0,NaN,NaN,A
217,E4319816,12,3236,NaN,N,2350.0,Lease,2018-12-10 00:00:00.0,NaN,NaN,A
221,C4345666,01,4101,NaN,N,3600.0,Lease,2019-01-25 00:00:00.0,NaN,NaN,A
225,C4342902,01,3001,NaN,N,2250.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
226,E4334631,04,304,NaN,N,2950.0,Lease,2019-01-11 00:00:00.0,NaN,NaN,A
227,C4342917,Th7,Th7,NaN,N,5000.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
230,E4334149,15,3006,NaN,N,2300.0,Lease,2019-01-10 00:00:00.0,NaN,NaN,A
232,W4346203,03,2003,NaN,N,3350.0,Lease,2019-01-26 00:00:00.0,NaN,NaN,A
233,C4342897,5,1705,NaN,N,2950.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
239,E4323946,09,1509,NaN,N,2000.0,Lease,2018-12-18 00:00:00.0,NaN,NaN,A
240,E4338126,381,NaN,NaN,N,1800.0,Lease,2019-01-15 00:00:00.0,NaN,NaN,A
247,E4323932,12,512,NaN,N,2300.0,Lease,2018-12-18 00:00:00.0,NaN,NaN,A
253,E4331455,6,913,NaN,N,1980.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
259,C4343737,01,201,NaN,N,2350.0,Lease,2019-01-23 00:00:00.0,NaN,NaN,A
261,E4325583,4,805,NaN,N,2000.0,Lease,2018-12-21 00:00:00.0,NaN,NaN,A
266,E4340112,6,Ph6,NaN,Y,2750.0,Lease,2019-01-17 00:00:00.0,NaN,NaN,A
268,E4336836,03,2503,NaN,N,2150.0,Lease,2019-01-14 00:00:00.0,NaN,NaN,A
270,E4334303,15,2206,NaN,N,1950.0,Lease,2019-01-10 00:00:00.0,NaN,NaN,A
271,E4336287,11,1211,NaN,N,2200.0,Lease,2019-01-14 00:00:00.0,NaN,NaN,A
285,E4333123,1032,1032,NaN,Y,1800.0,Lease,2019-01-09 00:00:00.0,NaN,NaN,A
302,E4339934,05,2105,NaN,N,2995.0,Lease,2019-01-17 00:00:00.0,NaN,NaN,A
309,N4343860,14,20,NaN,N,2200.0,Lease,2019-01-23 00:00:00.0,NaN,NaN,A
315,E4337591,8,1208,NaN,N,2400.0,Lease,2019-01-15 00:00:00.0,NaN,NaN,A
318,E4332920,4,Ph 04,NaN,N,2200.0,Lease,2019-01-09 00:00:00.0,NaN,NaN,A
322,E4334054,10,3410,NaN,N,2300.0,Lease,2019-01-10 00:00:00.0,NaN,NaN,A
323,E4338187,9,2530,NaN,N,2200.0,Lease,2019-01-16 00:00:00.0,NaN,NaN,A
324,E4326874,6,1907,NaN,N,2200.0,Lease,2018-12-29 00:00:00.0,NaN,NaN,A
328,W4342982,11,1011,NaN,N,2400.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
331,E4338631,414,NaN,NaN,N,1850.0,Lease,2019-01-16 00:00:00.0,NaN,NaN,A
334,E4338518,10,711,NaN,N,2100.0,Lease,2019-01-16 00:00:00.0,NaN,NaN,A
337,E4331758,12,806,NaN,Y,1900.0,Lease,2019-01-08 00:00:00.0,NaN,NaN,A
342,E4331254,11,304,NaN,N,2200.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
343,C4256372,06,3606,NaN,N,4000.0,Lease,2018-09-23 00:00:00.0,NaN,NaN,A
352,E4335785,380,NaN,NaN,N,1800.0,Lease,2019-01-13 00:00:00.0,NaN,NaN,A
353,C4221447,04,4304,NaN,N,3750.0,Lease,2018-08-16 00:00:00.0,NaN,NaN,A
355,E4338649,5,521,NaN,Y,1250.0,Lease,2019-01-16 00:00:00.0,NaN,NaN,A
356,E4337063,77,605,NaN,N,2300.0,Lease,2019-01-14 00:00:00.0,NaN,NaN,A
357,C4277332,08,2308,NaN,N,6000.0,Lease,2018-10-15 00:00:00.0,NaN,NaN,A
360,W4344402,10,210,NaN,N,1900.0,Lease,2019-01-24 00:00:00.0,NaN,NaN,A
361,E4335515,01,3101,NaN,N,2000.0,Lease,2019-01-12 00:00:00.0,NaN,NaN,A
366,E4340374,1,1215,NaN,N,1885.0,Lease,2019-01-18 00:00:00.0,NaN,NaN,A
368,E4341076,6,1007,NaN,N,2500.0,Lease,2019-01-18 00:00:00.0,NaN,NaN,A
372,C4243431,10,2410,NaN,N,4490.0,Lease,2018-09-11 00:00:00.0,NaN,NaN,A
389,C4267756,C,14C,NaN,N,9800.0,Lease,2018-10-04 00:00:00.0,NaN,NaN,A
394,E4340961,11,921,NaN,N,2200.0,Lease,2019-01-18 00:00:00.0,NaN,NaN,A
401,C4248297,1,Ph101,NaN,N,2800.0,Lease,2018-09-14 00:00:00.0,NaN,NaN,A
403,C4342972,17,202,NaN,N,2400.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
406,E4342975,31,2-Bsmnt,NaN,Y,1000.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
409,C4248834,03,4003,NaN,N,5750.0,Lease,2018-09-15 00:00:00.0,NaN,NaN,A
411,C4285138,02,4702,NaN,N,2580.0,Lease,2018-10-23 00:00:00.0,NaN,NaN,A
420,E4334008,4,304,NaN,N,2999.0,Lease,2019-01-10 00:00:00.0,NaN,NaN,A
421,C4211514,4,305,NaN,N,6000.0,Lease,2018-08-07 00:00:00.0,NaN,NaN,A
424,E4339199,13,913,NaN,N,1940.0,Lease,2019-01-16 00:00:00.0,NaN,NaN,A
426,E4340582,826,826,NaN,Y,2100.0,Lease,2019-01-18 00:00:00.0,NaN,NaN,A
427,E4322741,01,1101,NaN,N,2100.0,Lease,2018-12-14 00:00:00.0,NaN,NaN,A
429,C4278526,04,1704,NaN,N,2180.0,Lease,2018-10-16 00:00:00.0,NaN,NaN,A
430,C4246191,0,Parking,NaN,NaN,200.0,Lease,2018-09-13 00:00:00.0,NaN,NaN,A
431,E4335891,18,2418,NaN,N,1150.0,Lease,2019-01-13 00:00:00.0,NaN,NaN,A
432,C4230142,02,2702,NaN,N,2450.0,Lease,2018-08-27 00:00:00.0,NaN,NaN,A
434,C4342963,01,3701,NaN,N,2650.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
437,C4342967,10,1011,NaN,N,2700.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
439,N4345101,31,986,NaN,N,2200.0,Lease,2019-01-24 00:00:00.0,NaN,NaN,A
441,E4340679,21,Ph21,NaN,N,2250.0,Lease,2019-01-18 00:00:00.0,NaN,NaN,A
443,E4321818,04,1004,NaN,N,2200.0,Lease,2018-12-13 00:00:00.0,NaN,NaN,A
445,C4345169,7,2308,NaN,N,2750.0,Lease,2019-01-25 00:00:00.0,NaN,NaN,A
452,C4268002,10,601,NaN,N,6000.0,Lease,2018-10-04 00:00:00.0,NaN,NaN,A
453,C4285938,9,1710,NaN,N,2400.0,Lease,2018-10-24 00:00:00.0,NaN,NaN,A
456,E4339233,07,1907,NaN,N,2600.0,Lease,2019-01-16 00:00:00.0,NaN,NaN,A
457,C4290946,04,1704,NaN,N,2400.0,Lease,2018-10-31 00:00:00.0,NaN,NaN,A
460,E4339439,02,402,NaN,N,2600.0,Lease,2019-01-17 00:00:00.0,NaN,NaN,A
467,C4233980,06,3106,NaN,Y,6000.0,Lease,2018-09-01 00:00:00.0,NaN,NaN,A
473,E4326929,316,316,NaN,N,2000.0,Lease,2018-12-30 00:00:00.0,NaN,NaN,A
475,C4279478,33,733,NaN,Y,3500.0,Lease,2018-10-17 00:00:00.0,NaN,NaN,A
476,C4262263,10,1610,NaN,N,3850.0,Lease,2018-09-28 00:00:00.0,NaN,NaN,A
480,E4340570,11,211,NaN,N,2300.0,Lease,2019-01-18 00:00:00.0,NaN,NaN,A
486,C4284547,12,912,NaN,N,2900.0,Lease,2018-10-23 00:00:00.0,NaN,NaN,A
488,E4335846,02,402,NaN,N,2300.0,Lease,2019-01-13 00:00:00.0,NaN,NaN,A
491,C4286658,04,2704,NaN,N,4440.0,Lease,2018-10-25 00:00:00.0,NaN,NaN,A
494,E4337811,108,108,NaN,N,1800.0,Lease,2019-01-15 00:00:00.0,NaN,NaN,A
495,C4278584,01,406,NaN,N,5900.0,Lease,2018-10-16 00:00:00.0,NaN,NaN,A
499,C4267349,11,2211,NaN,N,2750.0,Lease,2018-10-04 00:00:00.0,NaN,NaN,A
505,C4234403,06,5306,NaN,N,3800.0,Lease,2018-09-03 00:00:00.0,NaN,NaN,A
506,C4278978,08,3608,NaN,N,3200.0,Lease,2018-10-17 00:00:00.0,NaN,NaN,A
513,C4290651,01,301,NaN,Y,2400.0,Lease,2018-10-30 00:00:00.0,NaN,NaN,A
516,C4252962,12,412,NaN,Y,2400.0,Lease,2018-09-19 00:00:00.0,NaN,NaN,A
519,C4270608,02,502,NaN,N,2700.0,Lease,2018-10-09 00:00:00.0,NaN,NaN,A
521,C4269627,#85,13,NaN,N,3250.0,Lease,2018-10-06 00:00:00.0,NaN,NaN,A
524,C4291478,11,511,NaN,N,2195.0,Lease,2018-10-31 00:00:00.0,NaN,NaN,A
...,...,...,...,...,...,...,...,...,...,...,...
204644,X4137962,2,2,NaN,N,1849.0,Lease,2018-05-23 00:00:00.0,NaN,NaN,U
204651,X4193095,01,T101,NaN,N,3400.0,Lease,2018-07-16 00:00:00.0,NaN,NaN,U
204652,X4197835,207,207,NaN,N,1300.0,Lease,2018-07-20 00:00:00.0,NaN,NaN,U
204669,X4186274,307,NaN,NaN,N,1250.0,Lease,2018-07-10 00:00:00.0,NaN,NaN,U
204681,X4215474,19,419,NaN,Y,650.0,Lease,2018-08-09 00:00:00.0,NaN,NaN,U
204685,X4166819,05,205,NaN,N,1150.0,Lease,2018-06-19 00:00:00.0,NaN,NaN,U
204688,X4193600,72,24,NaN,N,2250.0,Lease,2018-07-17 00:00:00.0,NaN,NaN,U
204697,X4171910,8C,8C,NaN,N,1400.0,Lease,2018-06-23 00:00:00.0,NaN,NaN,U
204698,X4172058,18,418,NaN,N,1500.0,Lease,2018-06-24 00:00:00.0,NaN,NaN,U
204699,X4214442,01,NaN,NaN,N,1700.0,Lease,2018-08-09 00:00:00.0,NaN,NaN,U
204709,X4191207,D165,NaN,NaN,N,1775.0,Lease,2018-07-13 00:00:00.0,NaN,NaN,U
204725,X4195524,15,315,NaN,N,1900.0,Lease,2018-07-18 00:00:00.0,NaN,NaN,U
204727,X4167558,14,14,NaN,N,1550.0,Lease,2018-06-20 00:00:00.0,NaN,NaN,U
204730,X4226250,5,5,NaN,N,2300.0,Lease,2018-08-22 00:00:00.0,NaN,NaN,U
204733,X4214770,2,1501,NaN,N,1400.0,Lease,2018-08-09 00:00:00.0,NaN,NaN,U
204747,X4184053,1,201,NaN,N,2150.0,Lease,2018-07-06 00:00:00.0,NaN,NaN,U
204750,X4198079,04,1104,NaN,N,2100.0,Lease,2018-07-20 00:00:00.0,NaN,NaN,U
204755,X4204971,1,9,NaN,N,2100.0,Lease,2018-07-29 00:00:00.0,NaN,NaN,U
204757,X4211433,302,302,NaN,N,1350.0,Lease,2018-08-07 00:00:00.0,NaN,NaN,U
204761,X4216974,13,307,NaN,N,1650.0,Lease,2018-08-11 00:00:00.0,NaN,NaN,U
204762,X4220502,11,111,NaN,N,1650.0,Lease,2018-08-15 00:00:00.0,NaN,NaN,U
204765,X4197616,2,906,NaN,N,2999.0,Lease,2018-07-20 00:00:00.0,NaN,NaN,U
204770,X4234572,3,2C,NaN,N,1995.0,Lease,2018-09-04 00:00:00.0,NaN,NaN,U
204777,X4189272,21,421,NaN,N,1500.0,Lease,2018-07-12 00:00:00.0,NaN,NaN,U
204778,X4203217,01,T101,NaN,N,3100.0,Lease,2018-07-26 00:00:00.0,NaN,NaN,U
204809,X4233596,6,6,NaN,N,2275.0,Lease,2018-08-31 00:00:00.0,NaN,NaN,U
204822,X4214881,38,38,NaN,N,1850.0,Lease,2018-08-09 00:00:00.0,NaN,NaN,U
204827,X4247686,6,6,NaN,N,2100.0,Lease,2018-09-14 00:00:00.0,NaN,NaN,U
204832,X4231584,12,18,NaN,N,1950.0,Lease,2018-08-29 00:00:00.0,NaN,NaN,U
204835,X4227928,7,7,NaN,N,1995.0,Lease,2018-08-24 00:00:00.0,380.0,NaN,U
204844,X4225336,9,709,NaN,N,1675.0,Lease,2018-08-21 00:00:00.0,571.0,NaN,U
204849,X4239564,2,Ph2,NaN,N,2200.0,Lease,2018-09-07 00:00:00.0,NaN,NaN,U
204851,X4257480,18,18,NaN,N,2000.0,Lease,2018-09-24 00:00:00.0,NaN,NaN,U
204855,X4224193,5,505,NaN,N,2550.0,Lease,2018-08-20 00:00:00.0,NaN,NaN,U
204861,X4258147,03,NaN,NaN,N,3150.0,Lease,2018-09-25 00:00:00.0,NaN,NaN,U
204872,X4238170,8,NaN,NaN,N,1450.0,Lease,2018-09-06 00:00:00.0,NaN,NaN,U
204920,X4240771,11,#511,NaN,N,1695.0,Lease,2018-09-07 00:00:00.0,NaN,NaN,U
204923,X4242597,22,44,NaN,N,1700.0,Lease,2018-09-10 00:00:00.0,NaN,NaN,U
204940,X4222836,7,7,NaN,N,750.0,Lease,2018-08-17 00:00:00.0,NaN,NaN,U
204945,X4237040,1,NaN,NaN,N,2500.0,Lease,2018-09-05 00:00:00.0,NaN,NaN,U
204958,X4246389,8,408,NaN,N,2000.0,Lease,2018-09-13 00:00:00.0,NaN,NaN,U
204976,X4264982,4,21C,NaN,N,1400.0,Lease,2018-10-02 00:00:00.0,NaN,NaN,U
204984,X4257280,/,NaN,NaN,N,1550.0,Lease,2018-09-24 00:00:00.0,NaN,NaN,U
205011,X4197002,11,711,NaN,N,1900.0,Lease,2018-07-19 00:00:00.0,NaN,NaN,U
205034,X4232147,05,605,NaN,Y,1300.0,Lease,2018-08-30 00:00:00.0,NaN,NaN,U
205036,X4258469,3,NaN,NaN,N,1850.0,Lease,2018-09-25 00:00:00.0,NaN,NaN,U
205045,X4255259,5,23,NaN,N,1700.0,Lease,2018-09-21 00:00:00.0,NaN,NaN,U
205050,X4244990,14,62,NaN,N,1950.0,Lease,2018-09-12 00:00:00.0,NaN,NaN,U
205056,X4242257,12,12,NaN,N,2350.0,Lease,2018-09-10 00:00:00.0,NaN,NaN,U
205066,X4223606,19,419,NaN,N,1550.0,Lease,2018-08-20 00:00:00.0,NaN,NaN,U
205076,X4257464,36,NaN,NaN,N,1750.0,Lease,2018-09-24 00:00:00.0,NaN,NaN,U
205079,X4218188,79,79,NaN,N,1700.0,Lease,2018-08-13 00:00:00.0,NaN,NaN,U
205083,X4259645,308,308,NaN,N,1350.0,Lease,2018-09-26 00:00:00.0,NaN,NaN,U
205093,X4255095,3,NaN,NaN,N,1575.0,Lease,2018-09-21 00:00:00.0,NaN,NaN,U
205096,X4272767,18,18,NaN,N,1849.0,Lease,2018-10-10 00:00:00.0,NaN,NaN,U
205097,X4262468,4,4,NaN,N,2000.0,Lease,2018-09-28 00:00:00.0,NaN,NaN,U
205116,X4255038,Na,NaN,NaN,N,1795.0,Lease,2018-09-21 00:00:00.0,NaN,NaN,U
205123,X4242728,4,4,NaN,N,1800.0,Lease,2018-09-10 00:00:00.0,NaN,NaN,U
205133,X4254974,0,NaN,NaN,N,1775.0,Lease,2018-09-21 00:00:00.0,NaN,NaN,U
205145,X4266520,402,402,NaN,N,1900.0,Lease,2018-10-03 00:00:00.0,NaN,NaN,U
205153,X4272829,01,701,NaN,N,2199.0,Lease,2018-10-10 00:00:00.0,NaN,NaN,U
205154,X4141679,5,705,NaN,N,2000.0,Lease,2018-05-27 00:00:00.0,NaN,NaN,U
205163,X4281115,8,NaN,NaN,N,2100.0,Lease,2018-10-18 00:00:00.0,NaN,NaN,U
205164,X4238450,1,21,NaN,N,2050.0,Lease,2018-09-06 00:00:00.0,NaN,NaN,U
205176,X4256047,15,NaN,NaN,N,1700.0,Lease,2018-09-22 00:00:00.0,NaN,NaN,U
205186,X4278703,1,NaN,NaN,N,1895.0,Lease,2018-10-16 00:00:00.0,NaN,NaN,U
205190,X4274758,05,105,NaN,N,1900.0,Lease,2018-10-12 00:00:00.0,NaN,NaN,U
205225,X4232069,27,427,NaN,N,1300.0,Lease,2018-08-30 00:00:00.0,NaN,NaN,U
205229,X4282350,12,212,NaN,N,1250.0,Lease,2018-10-20 00:00:00.0,NaN,NaN,U
205230,X4266976,11,511,NaN,N,2150.0,Lease,2018-10-03 00:00:00.0,NaN,NaN,U
205232,X4229033,05,105,NaN,N,1950.0,Lease,2018-08-25 00:00:00.0,NaN,NaN,U
205236,X4255446,1,1,NaN,N,2000.0,Lease,2018-09-21 00:00:00.0,NaN,NaN,U
205258,X4285649,11,511,NaN,N,2000.0,Lease,2018-10-24 00:00:00.0,NaN,NaN,U
205265,X4278387,13,413,NaN,N,1900.0,Lease,2018-10-16 00:00:00.0,NaN,NaN,U
205274,X4258549,422,422,NaN,N,1650.0,Lease,2018-09-25 00:00:00.0,NaN,NaN,U
205289,X4266627,4,504,NaN,N,1550.0,Lease,2018-10-03 00:00:00.0,NaN,NaN,U
205315,X4284947,10,314,NaN,N,2200.0,Lease,2018-10-23 00:00:00.0,NaN,NaN,U
205324,X4297451,5,1405,NaN,Y,1100.0,Lease,2018-11-07 00:00:00.0,NaN,NaN,U
205332,X4308665,9,NaN,NaN,N,1700.0,Lease,2018-11-21 00:00:00.0,NaN,NaN,U
205335,X4285756,1,NaN,NaN,N,1850.0,Lease,2018-10-24 00:00:00.0,NaN,NaN,U
205353,X4233379,B1,B1,NaN,N,1500.0,Lease,2018-08-31 00:00:00.0,NaN,NaN,U
205386,X4282009,36,36,NaN,N,1750.0,Lease,2018-10-19 00:00:00.0,NaN,NaN,U
205387,X4257146,0,NaN,NaN,N,1700.0,Lease,2018-09-24 00:00:00.0,NaN,NaN,U
205390,X4257460,35,35,NaN,N,1800.0,Lease,2018-09-24 00:00:00.0,NaN,NaN,U
205391,X4277856,18,118,NaN,N,1450.0,Lease,2018-10-16 00:00:00.0,NaN,NaN,U
205394,X4302323,28,528,NaN,N,1850.0,Lease,2018-11-13 00:00:00.0,NaN,NaN,U
205406,X4295903,15,#1017,NaN,N,1450.0,Lease,2018-11-06 00:00:00.0,NaN,NaN,U
205430,X4296077,4,NaN,NaN,N,1875.0,Lease,2018-11-06 00:00:00.0,NaN,NaN,U
205436,X4258648,12,18,NaN,N,1925.0,Lease,2018-09-25 00:00:00.0,NaN,NaN,U
205440,X4283316,04,504,NaN,N,1600.0,Lease,2018-10-22 00:00:00.0,NaN,NaN,U
205441,X4286511,98,NaN,NaN,N,2099.0,Lease,2018-10-25 00:00:00.0,NaN,NaN,U
205442,X4289596,16,NaN,NaN,N,3300.0,Lease,2018-10-29 00:00:00.0,NaN,NaN,U
205445,X4264712,A,A,NaN,N,1600.0,Lease,2018-10-02 00:00:00.0,NaN,NaN,U
205449,X4319981,41,41,NaN,NaN,1850.0,Lease,2018-12-10 00:00:00.0,259.0,2938.0,U
205453,X4289322,57,57,NaN,N,2100.0,Lease,2018-10-29 00:00:00.0,NaN,NaN,U
205457,X4269289,49,49,NaN,N,2000.0,Lease,2018-10-05 00:00:00.0,NaN,NaN,U
205470,X4315162,12,312,NaN,Y,1450.0,Lease,2018-12-02 00:00:00.0,NaN,NaN,U
205471,X4294183,8,8,NaN,N,1975.0,Lease,2018-11-03 00:00:00.0,NaN,NaN,U
205473,X4286508,98,NaN,NaN,N,2099.0,Lease,2018-10-25 00:00:00.0,NaN,NaN,U
205474,X4293129,13,204,NaN,N,2500.0,Lease,2018-11-02 00:00:00.0,NaN,NaN,U
205492,X4310573,66A,66B,NaN,N,1600.0,Lease,2018-11-24 00:00:00.0,NaN,NaN,U
205504,X4328795,46,NaN,NaN,N,3100.0,Lease,2019-01-03 00:00:00.0,NaN,NaN,U
205510,X4318031,21,21,NaN,N,2000.0,Lease,2018-12-06 00:00:00.0,NaN,NaN,U
205514,X4325056,7,7,NaN,N,1950.0,Lease,2018-12-20 00:00:00.0,NaN,NaN,U
205515,X4296973,608,#608,NaN,N,2500.0,Lease,2018-11-07 00:00:00.0,NaN,NaN,U
205540,X4334934,602,602,NaN,N,1600.0,Lease,2019-01-11 00:00:00.0,NaN,NaN,U
205548,X4326566,D165,NaN,NaN,N,1875.0,Lease,2018-12-28 00:00:00.0,NaN,NaN,U
205551,X4321616,27,27,NaN,N,1950.0,Lease,2018-12-12 00:00:00.0,134.0,NaN,U
205556,X4231565,NaN,26,NaN,Y,1799.0,Lease,2018-08-29 00:00:00.0,NaN,NaN,U
205558,X4310330,66F,NaN,NaN,N,1550.0,Lease,2018-11-23 00:00:00.0,NaN,NaN,U
205560,X4325727,08,208,NaN,N,1295.0,Lease,2018-12-22 00:00:00.0,NaN,NaN,U
205571,X4323304,4,404,NaN,N,1750.0,Lease,2018-12-17 00:00:00.0,NaN,NaN,U
205585,X4285488,35,35,NaN,N,1800.0,Lease,2018-10-24 00:00:00.0,NaN,NaN,U
205586,X4316868,98,NaN,NaN,N,2050.0,Lease,2018-12-04 00:00:00.0,NaN,NaN,U
205588,X4324826,419,419,NaN,N,1300.0,Lease,2018-12-20 00:00:00.0,NaN,NaN,U
205589,X4248668,1,9,NaN,N,2200.0,Lease,2018-09-15 00:00:00.0,NaN,NaN,U
205605,X4276460,9,#314,NaN,N,1350.0,Lease,2018-10-15 00:00:00.0,NaN,NaN,U
205612,X4322371,98,NaN,NaN,N,1990.0,Lease,2018-12-14 00:00:00.0,NaN,NaN,U
205613,X4266519,410,410,NaN,N,1900.0,Lease,2018-10-03 00:00:00.0,NaN,NaN,U
205617,X4281889,507,507,NaN,N,1800.0,Lease,2018-10-19 00:00:00.0,NaN,NaN,U
205618,X4291651,22,22,NaN,N,1200.0,Lease,2018-10-31 00:00:00.0,NaN,NaN,U
205625,X4322311,7,23,NaN,N,1850.0,Lease,2018-12-14 00:00:00.0,NaN,NaN,U
205626,X4336574,28,128,NaN,N,1550.0,Lease,2019-01-14 00:00:00.0,0.0,NaN,U
205630,X4320312,10,10,NaN,N,2249.0,Lease,2018-12-10 00:00:00.0,NaN,NaN,U

In [84]:
No_maint =df['Maint'].isnull().sum()

In [85]:
print(No_maint)

88311

In [86]:
df_filter=df.query('S_r=="Lease"')
Sold_listing_lease=df_filter.Ml_num.count()

In [87]:
print(Sold_listing_lease)

89813

In [103]:
df.loc[(df['Status'] == 'A') & (df['S_r'] == 'Lease') & (df['Maint'].isnull())]

,Ml_num,Unit_num,Apt_num,Addl_mo_fee,All_inc,Lp_dol,S_r,Input_date,Maint,Taxes,Status
2,E4328538,322,322,NaN,N,1550.0,Lease,2019-01-03 00:00:00.0,NaN,NaN,A
7,E4329715,3,Unit 2,NaN,N,3500.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
15,E4319152,04,1104,NaN,N,1850.0,Lease,2018-12-07 00:00:00.0,NaN,NaN,A
18,E4329395,2505,2505,NaN,N,2000.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
22,E4310550,0,NaN,NaN,Y,2895.0,Lease,2018-11-24 00:00:00.0,NaN,NaN,A
23,E4316679,03,1303,NaN,N,2100.0,Lease,2018-12-04 00:00:00.0,NaN,NaN,A
24,E4327584,10,310,NaN,N,1650.0,Lease,2019-01-02 00:00:00.0,NaN,NaN,A
31,E4314076,09,709,NaN,N,1750.0,Lease,2018-11-30 00:00:00.0,NaN,NaN,A
39,E4316498,05,Ph 05,NaN,N,6000.0,Lease,2018-12-04 00:00:00.0,NaN,NaN,A
44,E4329606,4,609-4,NaN,N,1700.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
52,E4329443,9,1609,NaN,N,2300.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
53,E4316611,04,Bedroom,NaN,N,1100.0,Lease,2018-12-04 00:00:00.0,NaN,NaN,A
54,E4329220,20,2420,NaN,N,2100.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
57,E4330443,01,501,NaN,N,2450.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
64,E4329473,303,303,NaN,N,1295.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
65,C4342920,11,1311,NaN,N,2500.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
67,E4322140,23,23,NaN,N,2550.0,Lease,2018-12-13 00:00:00.0,NaN,NaN,A
74,E4316597,04,1504,NaN,N,2350.0,Lease,2018-12-04 00:00:00.0,NaN,NaN,A
78,E4316405,184,184,NaN,N,2300.0,Lease,2018-12-04 00:00:00.0,NaN,NaN,A
80,E4316960,7,1507,NaN,N,2500.0,Lease,2018-12-05 00:00:00.0,NaN,NaN,A
88,E4314208,04,604,NaN,N,2200.0,Lease,2018-11-30 00:00:00.0,NaN,NaN,A
89,E4321191,19,1019,NaN,N,2000.0,Lease,2018-12-12 00:00:00.0,NaN,NaN,A
92,E4322154,09,1809,NaN,Y,2800.0,Lease,2018-12-13 00:00:00.0,NaN,NaN,A
93,E4332008,7,907,NaN,N,1500.0,Lease,2019-01-08 00:00:00.0,NaN,NaN,A
96,E4330598,03,3303,NaN,N,2000.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
101,E4326548,8,908,NaN,N,1900.0,Lease,2018-12-28 00:00:00.0,NaN,NaN,A
102,E4328010,13,1113,NaN,N,1950.0,Lease,2019-01-02 00:00:00.0,NaN,NaN,A
103,E4327712,32,NaN,NaN,N,2600.0,Lease,2019-01-02 00:00:00.0,NaN,NaN,A
104,E4329656,18,1919,NaN,N,2000.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
109,E4331111,07,807,NaN,N,1800.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
116,E4327850,10,510,NaN,N,2050.0,Lease,2019-01-02 00:00:00.0,NaN,NaN,A
129,E4336279,01,701,NaN,N,2350.0,Lease,2019-01-14 00:00:00.0,NaN,NaN,A
131,E4326073,09,2209,NaN,N,2300.0,Lease,2018-12-24 00:00:00.0,NaN,NaN,A
138,C4342908,11,1211,NaN,N,2250.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
139,E4332218,02,902,NaN,N,2200.0,Lease,2019-01-08 00:00:00.0,NaN,NaN,A
141,E4330856,12,1715,NaN,N,1950.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
146,E4329253,12,1712,NaN,N,1675.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
148,E4331280,15,3415,NaN,N,1850.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
153,C4342901,01,1701,NaN,N,2600.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
154,E4327000,15,415,NaN,N,1880.0,Lease,2018-12-31 00:00:00.0,NaN,NaN,A
156,E4332885,10,1210,NaN,N,1975.0,Lease,2019-01-09 00:00:00.0,NaN,NaN,A
161,E4329763,6,6,NaN,N,2650.0,Lease,2019-01-04 00:00:00.0,NaN,NaN,A
164,E4336424,0,208,NaN,N,2500.0,Lease,2019-01-14 00:00:00.0,NaN,NaN,A
166,W4342942,15,1629,NaN,N,1930.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
167,E4320694,2,3102,NaN,N,2400.0,Lease,2018-12-11 00:00:00.0,NaN,NaN,A
169,E4324340,9,810,NaN,N,1900.0,Lease,2018-12-19 00:00:00.0,NaN,NaN,A
174,E4332896,07,#207,NaN,N,2200.0,Lease,2019-01-09 00:00:00.0,NaN,NaN,A
177,C4342905,05,1115,NaN,N,2000.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
179,E4334932,14,1414,NaN,N,1875.0,Lease,2019-01-11 00:00:00.0,NaN,NaN,A
184,E4336471,312,312,NaN,N,1850.0,Lease,2019-01-14 00:00:00.0,NaN,NaN,A
185,E4316219,3335,3335,NaN,N,2100.0,Lease,2018-12-04 00:00:00.0,NaN,NaN,A
188,C4342931,4,2504,NaN,N,2200.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
198,E4334144,3,1003,NaN,N,2300.0,Lease,2019-01-10 00:00:00.0,NaN,NaN,A
200,E4335440,10,510,NaN,N,1900.0,Lease,2019-01-12 00:00:00.0,NaN,NaN,A
202,E4323846,14,2014,NaN,N,2200.0,Lease,2018-12-18 00:00:00.0,NaN,NaN,A
203,E4322610,19,19,NaN,N,2150.0,Lease,2018-12-14 00:00:00.0,NaN,NaN,A
207,E4330666,14,414,NaN,N,2100.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
209,E4334266,1,1808,NaN,N,700.0,Lease,2019-01-10 00:00:00.0,NaN,NaN,A
212,E4333152,03,303,NaN,N,3500.0,Lease,2019-01-09 00:00:00.0,NaN,NaN,A
213,E4328090,2,Unit 3,NaN,N,2800.0,Lease,2019-01-02 00:00:00.0,NaN,NaN,A
217,E4319816,12,3236,NaN,N,2350.0,Lease,2018-12-10 00:00:00.0,NaN,NaN,A
221,C4345666,01,4101,NaN,N,3600.0,Lease,2019-01-25 00:00:00.0,NaN,NaN,A
225,C4342902,01,3001,NaN,N,2250.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
226,E4334631,04,304,NaN,N,2950.0,Lease,2019-01-11 00:00:00.0,NaN,NaN,A
227,C4342917,Th7,Th7,NaN,N,5000.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
230,E4334149,15,3006,NaN,N,2300.0,Lease,2019-01-10 00:00:00.0,NaN,NaN,A
232,W4346203,03,2003,NaN,N,3350.0,Lease,2019-01-26 00:00:00.0,NaN,NaN,A
233,C4342897,5,1705,NaN,N,2950.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
239,E4323946,09,1509,NaN,N,2000.0,Lease,2018-12-18 00:00:00.0,NaN,NaN,A
240,E4338126,381,NaN,NaN,N,1800.0,Lease,2019-01-15 00:00:00.0,NaN,NaN,A
247,E4323932,12,512,NaN,N,2300.0,Lease,2018-12-18 00:00:00.0,NaN,NaN,A
253,E4331455,6,913,NaN,N,1980.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
259,C4343737,01,201,NaN,N,2350.0,Lease,2019-01-23 00:00:00.0,NaN,NaN,A
261,E4325583,4,805,NaN,N,2000.0,Lease,2018-12-21 00:00:00.0,NaN,NaN,A
266,E4340112,6,Ph6,NaN,Y,2750.0,Lease,2019-01-17 00:00:00.0,NaN,NaN,A
268,E4336836,03,2503,NaN,N,2150.0,Lease,2019-01-14 00:00:00.0,NaN,NaN,A
270,E4334303,15,2206,NaN,N,1950.0,Lease,2019-01-10 00:00:00.0,NaN,NaN,A
271,E4336287,11,1211,NaN,N,2200.0,Lease,2019-01-14 00:00:00.0,NaN,NaN,A
285,E4333123,1032,1032,NaN,Y,1800.0,Lease,2019-01-09 00:00:00.0,NaN,NaN,A
302,E4339934,05,2105,NaN,N,2995.0,Lease,2019-01-17 00:00:00.0,NaN,NaN,A
309,N4343860,14,20,NaN,N,2200.0,Lease,2019-01-23 00:00:00.0,NaN,NaN,A
315,E4337591,8,1208,NaN,N,2400.0,Lease,2019-01-15 00:00:00.0,NaN,NaN,A
318,E4332920,4,Ph 04,NaN,N,2200.0,Lease,2019-01-09 00:00:00.0,NaN,NaN,A
322,E4334054,10,3410,NaN,N,2300.0,Lease,2019-01-10 00:00:00.0,NaN,NaN,A
323,E4338187,9,2530,NaN,N,2200.0,Lease,2019-01-16 00:00:00.0,NaN,NaN,A
324,E4326874,6,1907,NaN,N,2200.0,Lease,2018-12-29 00:00:00.0,NaN,NaN,A
328,W4342982,11,1011,NaN,N,2400.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
331,E4338631,414,NaN,NaN,N,1850.0,Lease,2019-01-16 00:00:00.0,NaN,NaN,A
334,E4338518,10,711,NaN,N,2100.0,Lease,2019-01-16 00:00:00.0,NaN,NaN,A
337,E4331758,12,806,NaN,Y,1900.0,Lease,2019-01-08 00:00:00.0,NaN,NaN,A
342,E4331254,11,304,NaN,N,2200.0,Lease,2019-01-07 00:00:00.0,NaN,NaN,A
343,C4256372,06,3606,NaN,N,4000.0,Lease,2018-09-23 00:00:00.0,NaN,NaN,A
352,E4335785,380,NaN,NaN,N,1800.0,Lease,2019-01-13 00:00:00.0,NaN,NaN,A
353,C4221447,04,4304,NaN,N,3750.0,Lease,2018-08-16 00:00:00.0,NaN,NaN,A
355,E4338649,5,521,NaN,Y,1250.0,Lease,2019-01-16 00:00:00.0,NaN,NaN,A
356,E4337063,77,605,NaN,N,2300.0,Lease,2019-01-14 00:00:00.0,NaN,NaN,A
357,C4277332,08,2308,NaN,N,6000.0,Lease,2018-10-15 00:00:00.0,NaN,NaN,A
360,W4344402,10,210,NaN,N,1900.0,Lease,2019-01-24 00:00:00.0,NaN,NaN,A
361,E4335515,01,3101,NaN,N,2000.0,Lease,2019-01-12 00:00:00.0,NaN,NaN,A
366,E4340374,1,1215,NaN,N,1885.0,Lease,2019-01-18 00:00:00.0,NaN,NaN,A
368,E4341076,6,1007,NaN,N,2500.0,Lease,2019-01-18 00:00:00.0,NaN,NaN,A
372,C4243431,10,2410,NaN,N,4490.0,Lease,2018-09-11 00:00:00.0,NaN,NaN,A
389,C4267756,C,14C,NaN,N,9800.0,Lease,2018-10-04 00:00:00.0,NaN,NaN,A
394,E4340961,11,921,NaN,N,2200.0,Lease,2019-01-18 00:00:00.0,NaN,NaN,A
401,C4248297,1,Ph101,NaN,N,2800.0,Lease,2018-09-14 00:00:00.0,NaN,NaN,A
403,C4342972,17,202,NaN,N,2400.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
406,E4342975,31,2-Bsmnt,NaN,Y,1000.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
409,C4248834,03,4003,NaN,N,5750.0,Lease,2018-09-15 00:00:00.0,NaN,NaN,A
411,C4285138,02,4702,NaN,N,2580.0,Lease,2018-10-23 00:00:00.0,NaN,NaN,A
420,E4334008,4,304,NaN,N,2999.0,Lease,2019-01-10 00:00:00.0,NaN,NaN,A
421,C4211514,4,305,NaN,N,6000.0,Lease,2018-08-07 00:00:00.0,NaN,NaN,A
424,E4339199,13,913,NaN,N,1940.0,Lease,2019-01-16 00:00:00.0,NaN,NaN,A
426,E4340582,826,826,NaN,Y,2100.0,Lease,2019-01-18 00:00:00.0,NaN,NaN,A
427,E4322741,01,1101,NaN,N,2100.0,Lease,2018-12-14 00:00:00.0,NaN,NaN,A
429,C4278526,04,1704,NaN,N,2180.0,Lease,2018-10-16 00:00:00.0,NaN,NaN,A
430,C4246191,0,Parking,NaN,NaN,200.0,Lease,2018-09-13 00:00:00.0,NaN,NaN,A
431,E4335891,18,2418,NaN,N,1150.0,Lease,2019-01-13 00:00:00.0,NaN,NaN,A
432,C4230142,02,2702,NaN,N,2450.0,Lease,2018-08-27 00:00:00.0,NaN,NaN,A
434,C4342963,01,3701,NaN,N,2650.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
437,C4342967,10,1011,NaN,N,2700.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
439,N4345101,31,986,NaN,N,2200.0,Lease,2019-01-24 00:00:00.0,NaN,NaN,A
441,E4340679,21,Ph21,NaN,N,2250.0,Lease,2019-01-18 00:00:00.0,NaN,NaN,A
443,E4321818,04,1004,NaN,N,2200.0,Lease,2018-12-13 00:00:00.0,NaN,NaN,A
445,C4345169,7,2308,NaN,N,2750.0,Lease,2019-01-25 00:00:00.0,NaN,NaN,A
452,C4268002,10,601,NaN,N,6000.0,Lease,2018-10-04 00:00:00.0,NaN,NaN,A
453,C4285938,9,1710,NaN,N,2400.0,Lease,2018-10-24 00:00:00.0,NaN,NaN,A
456,E4339233,07,1907,NaN,N,2600.0,Lease,2019-01-16 00:00:00.0,NaN,NaN,A
457,C4290946,04,1704,NaN,N,2400.0,Lease,2018-10-31 00:00:00.0,NaN,NaN,A
460,E4339439,02,402,NaN,N,2600.0,Lease,2019-01-17 00:00:00.0,NaN,NaN,A
467,C4233980,06,3106,NaN,Y,6000.0,Lease,2018-09-01 00:00:00.0,NaN,NaN,A
473,E4326929,316,316,NaN,N,2000.0,Lease,2018-12-30 00:00:00.0,NaN,NaN,A
475,C4279478,33,733,NaN,Y,3500.0,Lease,2018-10-17 00:00:00.0,NaN,NaN,A
476,C4262263,10,1610,NaN,N,3850.0,Lease,2018-09-28 00:00:00.0,NaN,NaN,A
480,E4340570,11,211,NaN,N,2300.0,Lease,2019-01-18 00:00:00.0,NaN,NaN,A
486,C4284547,12,912,NaN,N,2900.0,Lease,2018-10-23 00:00:00.0,NaN,NaN,A
488,E4335846,02,402,NaN,N,2300.0,Lease,2019-01-13 00:00:00.0,NaN,NaN,A
491,C4286658,04,2704,NaN,N,4440.0,Lease,2018-10-25 00:00:00.0,NaN,NaN,A
494,E4337811,108,108,NaN,N,1800.0,Lease,2019-01-15 00:00:00.0,NaN,NaN,A
495,C4278584,01,406,NaN,N,5900.0,Lease,2018-10-16 00:00:00.0,NaN,NaN,A
499,C4267349,11,2211,NaN,N,2750.0,Lease,2018-10-04 00:00:00.0,NaN,NaN,A
505,C4234403,06,5306,NaN,N,3800.0,Lease,2018-09-03 00:00:00.0,NaN,NaN,A
506,C4278978,08,3608,NaN,N,3200.0,Lease,2018-10-17 00:00:00.0,NaN,NaN,A
513,C4290651,01,301,NaN,Y,2400.0,Lease,2018-10-30 00:00:00.0,NaN,NaN,A
516,C4252962,12,412,NaN,Y,2400.0,Lease,2018-09-19 00:00:00.0,NaN,NaN,A
519,C4270608,02,502,NaN,N,2700.0,Lease,2018-10-09 00:00:00.0,NaN,NaN,A
521,C4269627,#85,13,NaN,N,3250.0,Lease,2018-10-06 00:00:00.0,NaN,NaN,A
524,C4291478,11,511,NaN,N,2195.0,Lease,2018-10-31 00:00:00.0,NaN,NaN,A
525,C4192155,4,604,NaN,Y,2800.0,Lease,2018-07-16 00:00:00.0,NaN,NaN,A
526,C4263072,07,1007,NaN,N,2400.0,Lease,2018-09-30 00:00:00.0,NaN,NaN,A
527,C4264048,1040,1040,NaN,N,4980.0,Lease,2018-10-01 00:00:00.0,NaN,NaN,A
...,...,...,...,...,...,...,...,...,...,...,...
7651,C4342293,13,213,NaN,N,2800.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7652,W4341472,03,303,NaN,N,2050.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7654,C4346052,08,1608,NaN,N,2800.0,Lease,2019-01-26 00:00:00.0,NaN,NaN,A
7655,W4342304,07,2207,NaN,N,2000.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7656,C4342057,05,2811,NaN,N,3100.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7657,C4341910,03,2903,NaN,N,2700.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7658,C4342111,06,4406,NaN,N,2400.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7659,W4341962,03,2203,NaN,N,2200.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7661,W4341943,17,1709,NaN,N,2200.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7662,C4342340,10,2010,NaN,N,1900.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7664,N4341415,09,809,NaN,N,2450.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7665,W4346335,05,1205,NaN,N,2100.0,Lease,2019-01-27 00:00:00.0,NaN,NaN,A
7669,W4342372,01,1101,NaN,N,2250.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7670,C4342347,18,1906,NaN,N,3350.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7671,N4341961,28,532,NaN,N,1900.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7673,C4346255,2,4309,NaN,N,2200.0,Lease,2019-01-26 00:00:00.0,NaN,NaN,A
7676,C4342345,06,806,NaN,Y,2350.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7679,W4345510,1207,NaN,NaN,N,2000.0,Lease,2019-01-25 00:00:00.0,NaN,NaN,A
7681,C4341713,26,1726,NaN,N,2450.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7683,C4345490,D4,P2 #d4,NaN,NaN,60.0,Lease,2019-01-25 00:00:00.0,NaN,NaN,A
7684,C4342206,11,1113,NaN,N,2099.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7685,C4342508,10,510,NaN,N,1950.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7687,W4342711,2823,2823,NaN,N,2200.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
7688,C4341510,20,939,NaN,N,2300.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7691,N4341714,08,2108,NaN,N,1890.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7692,C4342733,8,809,NaN,N,2350.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
7693,W4342046,8,508,NaN,N,1950.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7694,C4342455,14,2117,NaN,Y,3200.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7697,C4346429,05,3505,NaN,N,2100.0,Lease,2019-01-27 00:00:00.0,NaN,NaN,A
7699,C4325825,9,1710,NaN,N,2700.0,Lease,2018-12-22 00:00:00.0,NaN,NaN,A
7701,C4342394,12,2212,NaN,N,2500.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7702,C4346359,02,1602,NaN,N,2500.0,Lease,2019-01-27 00:00:00.0,NaN,NaN,A
7703,C4342437,3,3403,NaN,N,7000.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7706,N4341512,8,8,NaN,N,2450.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7710,N4342384,33,66,NaN,N,2300.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7711,C4341508,03,1203,NaN,N,2000.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7712,C4341894,11,3311,NaN,N,2700.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7713,C4334869,12,1812,NaN,N,2200.0,Lease,2019-01-11 00:00:00.0,NaN,NaN,A
7714,E4342471,309,309,NaN,N,2300.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7715,W4341920,11,2011,NaN,N,3500.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7717,W4346350,08,1808,NaN,N,2200.0,Lease,2019-01-27 00:00:00.0,NaN,NaN,A
7718,C4342481,03,1803,NaN,N,2700.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7719,N4342241,24,601,NaN,N,2150.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7722,C4341796,01,1201,NaN,N,3100.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7723,C4341755,03,603,NaN,N,2300.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7724,C4341708,12,1912,NaN,N,2300.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7725,C4341937,1907,1907,NaN,Y,2195.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7726,C4341473,05,3105,NaN,N,2650.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7727,E4341683,2,812,NaN,N,2000.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7731,C4346362,608,608,NaN,N,2600.0,Lease,2019-01-27 00:00:00.0,NaN,NaN,A
7733,C4342452,G03,Parking,NaN,NaN,160.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7735,C4342721,01,801,NaN,N,7250.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
7737,X4341520,-,NaN,NaN,N,2195.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7741,C4341900,7,507,NaN,Y,3800.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7742,C4341902,07,2507,NaN,N,2200.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7743,C4341651,06,1707,NaN,N,3000.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7746,C4342613,24,224,NaN,N,2550.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
7748,C4341507,24,709,NaN,N,3995.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7751,C4346331,09,3610,NaN,N,2600.0,Lease,2019-01-27 00:00:00.0,NaN,NaN,A
7752,W4341444,4,304,NaN,N,1850.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7753,C4342465,13,2116,NaN,Y,3650.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7757,C4341496,09,1710,NaN,N,29000.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7759,C4341895,33,3404,NaN,N,2400.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7760,C4341908,03,3803,NaN,N,7780.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7761,C4342280,10,2211,NaN,N,2650.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7762,C4342313,46,646,NaN,N,2800.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7764,W4345945,706,706,NaN,N,1650.0,Lease,2019-01-25 00:00:00.0,NaN,NaN,A
7765,C4342643,9,2910,NaN,N,2200.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
7766,C4342585,11,311,NaN,N,2950.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
7768,C4346233,1,701,NaN,N,1850.0,Lease,2019-01-26 00:00:00.0,NaN,NaN,A
7770,C4341909,16,316,NaN,N,2095.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7775,N4341640,10,211,NaN,N,1900.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7776,C4342211,7,109,NaN,N,2250.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7778,N4342359,77,77,NaN,N,2795.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7781,C4341638,01,2201,NaN,N,3000.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7782,C4342276,03,803,NaN,N,3950.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7783,W4341798,01,1201,NaN,N,2480.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7784,C4341456,5,1502,NaN,N,2900.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7788,C4341779,34,639,NaN,N,2850.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7789,W4346368,12,912,NaN,Y,2150.0,Lease,2019-01-27 00:00:00.0,NaN,NaN,A
7795,W4345560,019,#103,NaN,N,1950.0,Lease,2019-01-25 00:00:00.0,NaN,NaN,A
7796,C4346254,7,2307,NaN,N,2750.0,Lease,2019-01-26 00:00:00.0,NaN,NaN,A
7798,C4346049,05,1005,NaN,N,2600.0,Lease,2019-01-26 00:00:00.0,NaN,NaN,A
7799,W4342033,269,269,NaN,N,1550.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7800,C4346118,6,1807,NaN,N,2400.0,Lease,2019-01-26 00:00:00.0,NaN,NaN,A
7806,W4341993,11,1011,NaN,N,1999.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7808,C4341556,08,508,NaN,N,2200.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7812,W4341577,05,1105,NaN,N,1975.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7816,N4341862,12,212C,NaN,N,1550.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7817,C4346193,8,3802,NaN,N,3550.0,Lease,2019-01-26 00:00:00.0,NaN,NaN,A
7818,W4345540,411,411,NaN,N,2600.0,Lease,2019-01-25 00:00:00.0,NaN,NaN,A
7819,C4341526,17,517,NaN,N,2799.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7824,W4341436,9,1809,NaN,N,1900.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7826,C4342369,04,4605,NaN,N,2300.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7833,N4341749,129,NaN,NaN,N,1900.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7835,W4342418,05,505,NaN,N,2400.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7848,C4342342,06,1906,NaN,N,2650.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7852,E4345785,07,207,NaN,N,1700.0,Lease,2019-01-25 00:00:00.0,NaN,NaN,A
7853,C4345561,7,2107,NaN,N,1980.0,Lease,2019-01-25 00:00:00.0,NaN,NaN,A
7854,C4346327,5,103,NaN,N,2200.0,Lease,2019-01-27 00:00:00.0,NaN,NaN,A
7855,C4346098,02,1201,NaN,N,2080.0,Lease,2019-01-26 00:00:00.0,NaN,NaN,A
7857,C4346264,11,1012,NaN,N,2250.0,Lease,2019-01-26 00:00:00.0,NaN,NaN,A
7859,W4346410,10,1810,NaN,N,3200.0,Lease,2019-01-27 00:00:00.0,NaN,NaN,A
7860,C4342393,6,3721,NaN,N,2350.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7861,E4346369,34,NaN,NaN,N,2400.0,Lease,2019-01-27 00:00:00.0,NaN,NaN,A
7864,W4341654,0,209,NaN,N,1900.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7865,C4341414,2401,2401,NaN,N,2550.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7869,W4342091,1708,1808,NaN,N,2100.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7876,C4342549,05,2005,NaN,N,2800.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
7880,C4342749,04,1804,NaN,Y,5000.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
7887,E4341727,5,1005,NaN,N,1750.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7888,C4341810,02,4202,NaN,N,1825.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7895,C4341866,10,3210,NaN,N,2350.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7916,C4341770,10,NaN,NaN,N,3700.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7924,C4341445,10,510,NaN,N,2100.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7925,N4341887,02,203D,NaN,N,1600.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7929,C4341738,06,606,NaN,N,2400.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7932,C4342718,611,611,NaN,N,2500.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
7933,C4342201,06,2007,NaN,Y,2250.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7934,C4341941,7,1208,NaN,N,3100.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7935,E4342271,12,612,NaN,N,2300.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7939,C4342133,9,310,NaN,N,2550.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A
7947,C4342696,09,903,NaN,N,2800.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
7952,C4341546,6,506,NaN,N,1785.0,Lease,2019-01-20 00:00:00.0,NaN,NaN,A
7953,N4342653,24,1009,NaN,N,1780.0,Lease,2019-01-22 00:00:00.0,NaN,NaN,A
7957,C4341960,7,307,NaN,N,1900.0,Lease,2019-01-21 00:00:00.0,NaN,NaN,A

In [104]:
df.loc[(df['Status'] == 'A') & (df['S_r'] == 'Sale') & (df['Maint'].isnull())]

Empty DataFrame
Columns: [Ml_num, Unit_num, Apt_num, Addl_mo_fee, All_inc, Lp_dol, S_r, Input_date, Maint, Taxes, Status]
Index: []